import Head from "next/head";
import { ArticlesCardsGrid } from "../components/Blogs";
import axios from "axios";
import { Footer } from "../components/Footer";
import HeaderSearch from "../components/HeaderSearch";
import { HeroImageRight } from "../components/HeroHeader";
import { useDispatch, useSelector } from "react-redux";

export default function Home(props) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <HeaderSearch />
      </header>
      <main>
        <HeroImageRight />
        <ArticlesCardsGrid
          data={props.blogData}
          cur={props.page}
          total={props.totalPages}
        />
      </main>
      <footer>
        <Footer />
      </footer>
    </div>
  );
}

export async function getServerSideProps({ req, res, query }) {
  let page;

  try {
    page = Number(query.page) || 1;

    const response = await axios.get(
      `http://tss.local/wp-json/wp/v2/posts?page=${page}&per_page=9&_embed`
    );

    const blogData = response;

    const totalPages = response.headers["x-wp-totalpages"];
    return {
      props: {
        blogData: blogData.data,
        totalPages: new Array(+totalPages).fill("item"),
        page,
      },
    };
  } catch (err) {
    return { redirect: { destination: "/" } };
  }
}
